# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Build to update nuget caches
    - cron: '15 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'windows-2022'
        build:
          - type: Debug
            vcpkg_cache: readwrite
          - type: Release
            vcpkg_cache: read
          - type: RelWithDebInfo
            vcpkg_cache: read
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: pwsh
    env:
      BUILD_TYPE: ${{ matrix.build.type }}
      NUGET_USERNAME: ${{ github.repository_owner }}
      NUGET_FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      NUGET_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,${{ matrix.build.vcpkg_cache }}"
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: check winget installed
      id: winget
      run: |
        $winget = (Get-Command winget -ErrorAction SilentlyContinue)
        "found=$([bool]($winget) -as [string])" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Install winget
      if: ${{ steps.winget.outputs.found == 'false' }}
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup development environment
      run: |
        .\tools\setup_devenv.ps1
        echo "CUDA_PATH=${Env:CUDA_PATH}" >> $Env:GITHUB_ENV
        echo "${Env:CUDA_PATH}\bin" >> $Env:GITHUB_PATH
        echo "${Env:CUDA_PATH}\bin\x64" >> $Env:GITHUB_PATH

    - name: Build (${{ env.BUILD_TYPE }})
      run: |
        .\tools\build.ps1 -build_type $Env:BUILD_TYPE
      env:
        BUILD_COMMIT: ${{ github.sha }}

    - name: Run tests (${{ env.BUILD_TYPE }})
      run: |
        .\tools\test.ps1 -build_type $Env:BUILD_TYPE
      env:
        TEST_DEBUG: ${{ runner.debug }}

    - name: Run app (${{ env.BUILD_TYPE }})
      run: |
        .\tools\envs.ps1
        & "${Env:SIMURATOR_EXE}" --help
        & "${Env:SIMURATOR_EXE}" --build-info
      env:
        SIMURATOR_EXE: .\build\${{ env.BUILD_TYPE }}\simurator.exe

  check-result:
    runs-on: ubuntu-slim
    needs: build
    if: failure() || cancelled()
    steps:
      - name: fail
        run: exit 1
